# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: weather_app_my_user
  password: 1
  database: weather_app_my_development

development:
  <<: *default

test:
  <<: *default
  database: weather_app_my_test

production:
  <<: *default
  database: weather_app_my_production
